version: 1
defaults:
  remote: github
  revision: main
  scheme: ssh
remotes:
  github:
    host: github.com
projects:
- name: madhavajay/htslib-rs
  path: repos/htslib-rs
  revision: main
- name: madhavajay/noodles
  path: repos/noodles
  revision: madhava/bioscript
provides:
- madhavajay/htslib-rs
- madhavajay/noodles
links:
- repo: madhavajay/htslib-rs
  at: vendor/rust/bcftools-rs/repos/htslib-rs
  branch: main
- repo: madhavajay/htslib-rs
  at: vendor/rust/htslib-rs
  branch: main
- repo: madhavajay/htslib-rs
  at: vendor/rust/samtools-rs/repos/htslib-rs
  branch: main
- repo: madhavajay/noodles
  at: noodles
  branch: madhava/bioscript
- repo: madhavajay/noodles
  at: repos/htslib-rs/repos/noodles
  branch: madhava/bioscript
