apiVersion: syftbox.openmined.org/v1alpha1
kind: Flow
metadata:
  name: brca-classifier
  version: 0.1.1
spec:
  inputs:
    samplesheet:
      type: List[GenotypeRecord]
  steps:
    - id: brca
      uses:
        source:
          kind: local
          path: ./
      with:
        participants: inputs.samplesheet
      publish:
        classification_result: File(result_BRCA.tsv)
      store:
        counts_sql:
          kind: sql
          source: classification_result
          table: brca_{run_id}
          key_column: participant_id
