apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: brca-classifier
  version: 0.1.1
  description: Classification of BRCA variants using ClinVar reference data for hereditary cancer risk.
  authors:
    - madhava@openmined.org
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: dynamic-nextflow
  assets:
    - path: classify_brca.py
    - path: brca2_clinvar.tsv
    - path: brca1_clinvar.tsv
  inputs:
    - name: participants
      type: List[GenotypeRecord]
      description: CSV/TSV with participant_id and genotype_file columns
      format:
        kind: csv
        mapping:
          participant_id: participant_id
          genotype_file: genotype_file
  outputs:
    - name: classification_result
      type: File
      description: BRCA variant classification (aggregated)
      format:
        kind: tsv
      path: result_BRCA.tsv
  parameters: []
