name: brca-classifier
inputs:
  samplesheet: List[GenotypeRecord]
steps:
- id: brca
  uses: ./
  with:
    participants: inputs.samplesheet
  publish:
    classification_result: File(result_BRCA.tsv)
  store:
    counts_sql:
      kind: sql
      destination: SQL()
      source: classification_result
      table_name: brca_{run_id}
      key_column: participant_id
