name: brca-classifier
author: madhava@openmined.org
workflow: workflow.nf
template: dynamic-nextflow
version: 0.1.0
assets:
- classify_brca.py
- brca2_clinvar.tsv
- brca1_clinvar.tsv
inputs:
- name: participants
  type: List[GenotypeRecord]
  description: CSV/TSV with participant_id and genotype_file columns
  format: csv
  mapping:
    participant_id: participant_id
    genotype_file: genotype_file
outputs:
- name: classification_result
  type: File
  description: BRCA variant classification (aggregated)
  format: tsv
  path: result_BRCA.tsv
