apiVersion: syftbox.openmined.org/v1alpha1
kind: Flow
metadata:
  name: herc2-classifier
  version: 0.1.1
spec:
  inputs:
    samplesheet:
      type: List[GenotypeRecord]
  steps:
    - id: herc2
      uses:
        source:
          kind: local
          path: ./
      with:
        participants: inputs.samplesheet
      publish:
        classification_result: File(result_HERC2.tsv)
      store:
        counts_sql:
          kind: sql
          source: classification_result
          table: herc2_{run_id}
          key_column: participant_id
