apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: herc2-classifier
  version: 0.1.1
  description: Classification of HERC2 genotypes for eye color prediction.
  authors:
    - madhava@openmined.org
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: dynamic-nextflow
  assets:
    - path: classify_herc2.py
  inputs:
    - name: participants
      type: List[GenotypeRecord]
      description: CSV/TSV with participant_id and genotype_file columns
      format:
        kind: csv
        mapping:
          participant_id: participant_id
          genotype_file: genotype_file
  outputs:
    - name: classification_result
      type: File
      description: HERC2 eye color classification (aggregated)
      format:
        kind: tsv
      path: result_HERC2.tsv
  parameters: []
