name: herc2-classifier
inputs:
  samplesheet: List[GenotypeRecord]
steps:
- id: herc2
  uses: ./
  with:
    participants: inputs.samplesheet
  publish:
    classification_result: File(result_HERC2.tsv)
  store:
    counts_sql:
      kind: sql
      destination: SQL()
      source: classification_result
      table_name: herc2_{run_id}
      key_column: participant_id
