name: herc2-classifier
author: madhava@openmined.org
workflow: workflow.nf
template: dynamic-nextflow
version: 0.1.0
docker_image: ghcr.io/openmined/bioscript:0.1.1
docker_platform: linux/amd64
assets:
- classify_herc2.py
inputs:
- name: genotype_file
  type: File
  description: Participant genotype TSV
  format: tsv
- name: data_dir
  type: Directory
  description: Base directory containing sample files
outputs:
- name: classification_result
  type: File
  description: HERC2 eye color classification
  format: tsv
  path: result_HERC2_{participant_id}.tsv
