name: herc2-classifier
author: madhava@openmined.org
workflow: workflow.nf
template: dynamic-nextflow
version: 0.1.1
assets:
- classify_herc2.py
inputs:
- name: participants
  type: List[GenotypeRecord]
  description: CSV/TSV with participant_id and genotype_file columns
  format: csv
  mapping:
    participant_id: participant_id
    genotype_file: genotype_file
outputs:
- name: classification_result
  type: File
  description: HERC2 eye color classification (aggregated)
  format: tsv
  path: result_HERC2.tsv
