apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: apol1-classifier
  version: 0.1.1
  authors:
  - madhava@openmined.org
  description: Classification of APOL1 genotypes (G0, G1, G2) for kidney disease risk assessment.
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: dynamic-nextflow
    image: ghcr.io/openmined/bioscript:0.1.6
  inputs:
  - name: participants
    type: List[GenotypeRecord]
    description: CSV/TSV with participant_id and genotype_file columns
    format:
      kind: csv
      mapping:
        participant_id: participant_id
        genotype_file: genotype_file
  outputs:
  - name: classification_result
    type: File
    description: APOL1 genotype classification
    format:
      kind: tsv
    path: result_APOL1.tsv
  - name: population_stats
    type: File
    description: APOL1 population allele statistics (aggregated)
    format:
      kind: tsv
    path: result_APOL1_stats.tsv
  - name: classification_stats
    type: File
    description: APOL1 status counts by allele class (G0/G1/G2) with hetero/homo split
    format:
      kind: tsv
    path: result_APOL1_classification_stats.tsv
  - name: apol1_status
    type: File
    description: Per-participant APOL1 status summary
    format:
      kind: tsv
    path: result_APOL1_status.tsv
  parameters: []
  assets:
  - path: classify_apol1.py
  - path: aggregate_population_stats.py
  - path: aggregate_classification_stats.py
  - path: aggregate_apol1_status.py
