apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: apol1-classifier
  version: 0.1.1
  description: Classification of APOL1 genotypes (G0, G1, G2) for kidney disease risk assessment.
  authors:
    - madhava@openmined.org
spec:
  runner:
    kind: nextflow
    entrypoint: workflow.nf
    template: dynamic-nextflow
  assets:
    - path: classify_apol1.py
  inputs:
    - name: participants
      type: List[GenotypeRecord]
      description: CSV/TSV with participant_id and genotype_file columns
      format:
        kind: csv
        mapping:
          participant_id: participant_id
          genotype_file: genotype_file
  outputs:
    - name: classification_result
      type: File
      description: APOL1 genotype classification
      format:
        kind: tsv
      path: result_APOL1.tsv
  parameters: []
