name: apol1-classifier
author: madhava@openmined.org
workflow: workflow.nf
template: dynamic-nextflow
version: 0.1.1
assets:
- classify_apol1.py
description: Classification of APOL1 genotypes (G0, G1, G2) for kidney disease risk assessment.
inputs:
- name: participants
  type: List[GenotypeRecord]
  description: CSV/TSV with participant_id and genotype_file columns
  format: csv
  mapping:
    participant_id: participant_id
    genotype_file: genotype_file
outputs:
- name: classification_result
  type: File
  description: APOL1 genotype classification
  format: tsv
  path: result_APOL1.tsv
