name: pipeline-apol1-classifier
author: madhava@openmined.org
workflow: workflow.nf
template: dynamic-nextflow
version: 0.1.0
assets:
- classify_apol1_exported.py
parameters: []
inputs:
- name: participants
  type: ParticipantSheet
  description: Participant metadata sheet with APOL1 genotype file references
  format: csv
- name: genotype_dir
  type: Directory
  description: Directory containing genotype files referenced by participants
outputs:
- name: apol1_sheet
  type: ParticipantSheet
  description: Samplesheet annotated with APOL1 genotype calls
  format: tsv
  path: apol1_participant_genotypes.tsv
