name: thalassemia-classifier
version: 0.1.1
inputs:
  samplesheet: List[GenotypeRecord]
steps:
- id: thalassemia
  uses: ./
  with:
    participants: inputs.samplesheet
  publish:
    classification_result: File(result_THALASSEMIA.tsv)
  store:
    counts_sql:
      kind: sql
      destination: SQL()
      source: classification_result
      table_name: thalassemia_{run_id}
      participant_column: participant_id
