name: thalassemia-classifier
author: madhava@openmined.org
workflow: workflow.nf
template: dynamic-nextflow
version: 0.1.1
assets:
- classify_thalassemia.py
- thalassemia_clinvar.tsv
description: Classification of thalassemia-associated variants using ClinVar reference data.
inputs:
- name: participants
  type: List[GenotypeRecord]
  description: CSV/TSV with participant_id and genotype_file columns
  format: csv
  mapping:
    participant_id: participant_id
    genotype_file: genotype_file
outputs:
- name: classification_result
  type: File
  description: Thalassemia variant classification (aggregated)
  format: tsv
  path: result_THALASSEMIA.tsv
